name = "Multicluster"
uuid = "15ffbdae-f567-4411-842e-188464567360"
authors = ["Francisco Heron de Carvalho Junior <heron@dc.ufc.br>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
MPIClusterManagers = "e7922434-ae4b-11e9-05c5-9780451d2c66"

[compat]
Distributed = "1.11.0"
MPIClusterManagers = "0.2.4"
